swagger: "2.0"
info:
  title: "Bookstore API"
  description: "API for managing books in a bookstore"
  version: "1.0.0"
basePath: "/"
schemes:
  - "http"
consumes:
  - "application/json"
produces:
  - "application/json"

paths:
  /test:
    get:
      summary: "Test endpoint"
      responses:
        200:
          description: "OK"
          schema:
            type: string
  /books:
    get:
      summary: "Get all books"
      responses:
        200:
          description: "OK"
          schema:
            type: array
            items:
              $ref: "#/definitions/Book"
    post:
      summary: "Add a new book"
      parameters:
        - in: body
          name: body
          description: "Book object"
          required: true
          schema:
            $ref: "#/definitions/NewBook"
      responses:
        201:
          description: "Created"
          schema:
            $ref: "#/definitions/Book"
  /books/{id}:
    get:
      summary: "Get a book by ID"
      parameters:
        - in: path
          name: id
          description: "ID of the book to retrieve"
          required: true
          type: integer
          format: int64
      responses:
        200:
          description: "OK"
          schema:
            $ref: "#/definitions/Book"
        404:
          description: "Book not found"
    put:
      summary: "Update a book by ID"
      parameters:
        - in: path
          name: id
          description: "ID of the book to update"
          required: true
          type: integer
          format: int64
        - in: body
          name: body
          description: "Updated book object"
          required: true
          schema:
            $ref: "#/definitions/NewBook"
      responses:
        200:
          description: "OK"
          schema:
            $ref: "#/definitions/Book"
        404:
          description: "Book not found"
    delete:
      summary: "Delete a book by ID"
      parameters:
        - in: path
          name: id
          description: "ID of the book to delete"
          required: true
          type: integer
          format: int64
      responses:
        200:
          description: "OK"
        404:
          description: "Book not found"

definitions:
  Book:
    type: object
    properties:
      id:
        type: integer
        format: int64
      title:
        type: string
      author:
        type: string
      publisher:
        type: string
    required:
      - id
      - title
      - author
      - publisher

  NewBook:
    type: object
    properties:
      title:
        type: string
      author:
        type: string
      publisher:
        type: string
    required:
      - title
      - author
      - publisher

